name: CharlesMcCallum
favicon: null
layout_spectrum: 1
typography_spectrum: 0.86881
title: Charles McCallum
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfefe'
    - '#645da1'
    - '#ebbeb0'
    - '#0a0005'
    - '#b42d3b'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
