title: Charles McCallum
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0.75
  brandColors:
    - '#000000'
    - '#c8be9a'
    - '#47645f'
    - '#00591d'
    - '#3e7d0d'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: CharlesMcCallum
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.86881
layout_spectrum: 0.17847
