name: CharlesMcCallum
favicon: null
layout_spectrum: 0.60396
typography_spectrum: 0.86881
title: Charles McCallum
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfefe'
    - '#685fa3'
    - '#f6c5b3'
    - '#0d0108'
    - '#2f2261'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
