name: CharlesMcCallum
favicon: null
layout_spectrum: 0.60396
typography_spectrum: 0.86881
title: Charles McCallum
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c8be9a'
    - '#47645f'
    - '#00591d'
    - '#3e7d0d'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
